version: '3.5'

volumes:
  housing_db: {}
  housing_media: {}
  housing_logs: {}

services:
  database:
    container_name: database_${APP_VERSION}
    restart: on-failure
    image: postgres:9.5
    volumes:
      - housing_db:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_USER=housing
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=housing
  
  webserver:
    container_name: webserver_${APP_VERSION}
    image: luizbraga/housing:${APP_VERSION}
    restart: always
    build: .
    volumes:
      - housing_media:/app/media/
      - housing_logs:/app/logs/
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://housing:password@database/housing
      - VIRTUAL_HOST=${APP_VERSION}.cadagente.tk
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      - database

networks:
  backend:
    name: housing_${APP_VERSION}
