version: '3.5'

volumes:
  db: {}
  media: {}
  static: {}
  staticfiles: {}
  logs: {}

services:
  database:
    container_name: database_${APP_VERSION}
    restart: on-failure
    image: postgres:9.5
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_USER=housing
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=housing
  
  webserver:
    container_name: webserver_${APP_VERSION}
    image: luizbraga/housing:${APP_VERSION}
    restart: always
    build: .
    volumes:
      - media:/app/src/media/
      - logs:/app/src/logs/
      - static:/app/src/static/
      - staticfiles:/app/src/staticfiles/
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://housing:password@database/housing
      - VIRTUAL_HOST=${APP_VERSION}.cadagente.tk
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      - database

networks:
  backend:
    name: housing_${APP_VERSION}
