version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - housing-{{ .Branch }}
          paths:
            - /caches/housing.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/housing.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=housing -t luizbraga/housing:${CIRCLE_BRANCH} .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/housing.tar luizbraga/housing:${CIRCLE_BRANCH}
      - save_cache:
          key: housing-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/housing.tar
      - run:
          name: Push application Docker image
          command: |
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push luizbraga/housing:${CIRCLE_BRANCH}